# Generated by Django 2.0.1 on 2018-01-18 15:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pratoPrincipal', models.TextField(max_length=30)),
                ('refeicao', models.TextField(max_length=30)),
                ('salada', models.TextField(max_length=30)),
                ('acompanhamento', models.TextField(max_length=30)),
                ('sobremesa', models.TextField(max_length=30)),
                ('observa', models.TextField(blank=True, null=True)),
                ('dataCap', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resData', models.DateField(default=datetime.date.today)),
                ('resHora', models.TimeField()),
                ('idCap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='cardapio.Cardapio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
